# Generated by Django 3.2.5 on 2023-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
