# Generated by Django 3.2.5 on 2023-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_auto_20230826_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
